### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Bosen-Zhang** [congxin95/DaFeC#1]
whether the framework provides the option of using GPU or not, and whether it is possible to experiment without using GPU

**Comment by congxin95** [comment]
I have updated my code, and now you can set the environment variable `CUDA_VISIBLE_DEVICES=""` to use CPU for experiments.

**Comment by Bosen-Zhang** [comment]
OK, thanks. But there is a errorTraceback (most recent call last):  
"train_demo.py", line 296, in <module>
    main()                              
  File "train_demo.py", line 274, in main                        
    pair=opt.pair,                                                                    
  File "/home/zbs/DaFeC-master/fewshot_re_kit/framework.py", line 157, in train             
    optimizer = pytorch_optim(parameters_to_optimize, lr=learning_rate, correct_bias=False)  
TypeError: __init__() got an unexpected keyword argument 'correct_bias'

**Comment by Bosen-Zhang** [comment]
or the question is
if I use BERT, what param should I change

**Comment by ShinTsong** [comment]
The `correct_bias` parameter (Line 157 in framework.py) is only for the `adamw` optimizer for BERT. 

If you want to use BERT, please use the `adamw `optimizer, you can add the cmd param `--optim adamw` or change the settings in the hyperparams.py.

If you would like to use other optimizer like SGD, please remove the `correct_bias` parameter.

**Comment by congxin95** [comment]
The correct_bias parameter (Line 157 in framework.py) is only for the adamw optimizer for BERT.

If you want to use BERT, please use the adamw optimizer, you can add the cmd param --optim adamw or change the settings in the hyperparams.py.

If you would like to use other optimizer like SGD, please remove the correct_bias parameter.

**Comment by Bosen-Zhang** [comment]
OK, thanks for your contribution
