### ISSUE TITLE
I have some questions in your paper and code

### ISSUE THREAD

**Issue by fsfwl11406** [congxin95/DaFeC#4]
Which code corresponds to Stage 4 in your paper ?Anneal_mode in your hyperparams is "cosine",but your code only use mode="hard",and where you give num_warmup_steps assignment.

**Comment by congxin95** [comment]
About Stage 4, you can refer `Step.3` in `Usage` part in `README.md`. Following the command, you can get the corresponding codes.

The `anneal_mode` is set as "cosine" in `hyperparams.py`. All of hyperparameters are set in `hyperparams.py` actually. Please check it. Thank you.
